version: 2.1
orbs:
  python: circleci/python@0.2.1

executors:
  meson_opensuse_builder:
    docker:
      - image: michaelbadcruble/opensuse-ci-sys
  meson_alpine_builder:
    docker:
      - image: michaelbadcruble/alpine-ci-sys
  meson_archlinux_builder:
    docker:
      - image: michaelbadcruble/arch-ci-sys
  meson_ubuntu_builder:
    docker:
      - image: michaelbadcruble/ubuntu-ci-sys
  meson_debain_builder:
    docker:
      - image: michaelbadcruble/debian-ci-sys
  meson_fedora_builder:
    docker:
      - image: michaelbadcruble/fedora-ci-sys

jobs:
  meson_opensuse_build:
    executor: meson_opensuse_builder
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: pytest -v run_unittests.py run_project_tests.py

  meson_alpine_build:
    executor: meson_alpine_builder
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: pytest -v run_unittests.py run_project_tests.py

  meson_archlinux_build:
    executor: meson_archlinux_builder
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: pytest -v run_unittests.py run_project_tests.py

  meson_ubuntu_build:
    executor: meson_ubuntu_builder
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: pytest -v run_unittests.py run_project_tests.py

  meson_debain_build:
    executor: meson_debain_builder
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: pytest -v run_unittests.py run_project_tests.py

  meson_fedora_build:
    executor: meson_fedora_builder
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: pytest -v run_unittests.py run_project_tests.py

workflows:
  version: 2
  linux_workflow:
    jobs:
      - meson_opensuse_build
      - meson_archlinux_build
      - meson_alpine_build
      - meson_ubuntu_build
      - meson_debain_build
      - meson_fedora_build
